' racing_quotes.bas -- the QuoteBank data and Quote$/FillIn$ that pick and
' fill a random line from it, split out of racing.bas so racing.bas's own
' code has room to grow: the full quote bank on top of the game no longer
' fit in the board's 128K program space. Loaded by racing.bas's very first
' statement (LIBRARY LOAD "B:/Games/racing_quotes.bas", RAM), which puts
' this in its own 128K PSRAM library slot -- separate from racing.bas's
' program space, and separate from the board's flash-saved library (the
' club's fonts), which this never touches and which is unaffected once
' the game exits. Build with: python mmbasic/build.py

Dim string qN$, qC$, qD$, qM$, qT$, qX$, qE$, qP$
Dim integer qLast(40)
' qSaid: one bit per line, set once that line's been said -- Quote$'s
' shuffle bag, so nobody hears the same mechanic/driver line twice until
' every line in that moment's bank has come up (then it reshuffles).
' 64 bits/category, so QuoteBank categories must stay at 64 lines or under
Dim integer qSaid(40)

' --- what they say: a bank of lines for each moment; Quote$ works through
' every line in a category before any of them repeat (see qSaid), so a
' long session doesn't start echoing itself. %N the player, %C the car,
' %D damage, %M money, %T lap time, %X target, %E what broke, %P a podium
' place ("1st"/"2nd"/"3rd"). Add lines freely: change a category's count
' to match, and keep it at 64 lines or under (qSaid's bitmask).
QuoteBank:
Data "WELCOME", 18
Data "Welcome to the team, %N!|The %C - good choice."
Data "G'day %N! The %C's yours.|Treat her gently. Or don't."
Data "New blood! %N, meet the %C.|She bites, but only a bit."
Data "So you're %N. The %C, eh?|Nice pick - she's quick."
Data "Welcome aboard, %N.|The %C's been waiting for you."
Data "%N! Fresh face. The %C|is fuelled and ready."
Data "Right, %N, you're in.|The %C won't drive itself."
Data "Another one! %N, meet|the %C. Don't scratch her."
Data "%N joins the club.|The %C's all yours now."
Data "Signed up, %N? Good.|The %C's out the back, keys in it."
Data "Heard good things, %N.|The %C'll test that."
Data "%N! Pull up a stool.|The %C's already warm."
Data "Fresh face in the pits, %N.|The %C's the pick of the litter."
Data "Welcome to the madhouse, %N.|The %C fits right in."
Data "%N, is it? The %C's|been waiting for someone like you."
Data "Good to have you, %N.|The %C won't know what hit it."
Data "Sign here, %N.|The %C's the rest of the deal."
Data "%N! Another mug for the grid.|The %C, God help you."
Data "WELCOMER", 18
Data "Can't wait to get out there!"
Data "Where's the throttle?"
Data "I was born for this."
Data "She's beautiful."
Data "Let's make some noise!"
Data "Do I get a trophy for turning up?"
Data "Finally, my racing career begins."
Data "I've watched every race on telly for this."
Data "Is there a seat, or am I standing?"
Data "Don't wait up, I'm winning this."
Data "Smells like victory in here."
Data "So this is what fame feels like."
Data "First round's on me. After I win."
Data "I brought my own lucky socks."
Data "Point me at the track."
Data "This is the best day of my life. So far."
Data "Somebody call my mum, I made it."
Data "Right, who do I have to beat?"
Data "BACK", 18
Data "Back again, %N?|The %C's ready to go."
Data "%N! Missed you, mate.|The %C's warmed up."
Data "Look who's back.|The %C's been polished for you."
Data "Right on time, %N.|Another go in the %C?"
Data "The %C again, %N?|Loyal - I like that."
Data "Oi %N! Tyres are on,|the %C's good to go."
Data "Couldn't stay away, %N?|The %C missed you too."
Data "%N returns! The %C's|out of the shed and ready."
Data "Back for more punishment, %N?|The %C's up for it."
Data "There you are, %N.|The %C's had a good rest."
Data "%N, as promised.|The %C's fuelled and eager."
Data "Round two, %N?|The %C's champing at the bit."
Data "Didn't think you'd be back so soon, %N.|The %C's ready regardless."
Data "%N! The regulars' seat's free.|The %C too."
Data "You again, %N. Good.|The %C was getting bored."
Data "Straight back for the %C, %N?|Can't say I blame you."
Data "%N's here - fire up the %C."
Data "Welcome back to the madness, %N.|The %C's exactly how you left her."
Data "BACKR", 18
Data "Let's win this one."
Data "Same as last time, but faster."
Data "Couldn't keep away."
Data "She knows the way by now."
Data "Put the kettle on, I'll be quick."
Data "Today's the day."
Data "Unfinished business out there."
Data "Missed this more than I'll admit."
Data "Round two - and I mean it this time."
Data "The track's been calling me all week."
Data "Let's see if I've still got it."
Data "No excuses today."
Data "Same car, new me."
Data "I've been dreaming about this corner."
Data "Back where I belong."
Data "Let's not talk about last time."
Data "Warmed the seat up on the drive over."
Data "Right, no mucking around this time."
Data "PRE_OK", 18
Data "She's running sweet.|Tyres are warm - go get 'em!"
Data "Not a mark on her, %N.|No excuses today!"
Data "Engine's purring like a kitten.|Well, a very loud kitten."
Data "%C's perfect. I've checked|everything twice. Three times."
Data "She's never been better.|Bring her back like that!"
Data "Fuel's in, tyres are hot.|Off you go, %N."
Data "0% damage, %N. Try and|keep it that way."
Data "The %C's mint. Go on,|make me proud."
Data "Nothing to report - she's|ready as she'll ever be."
Data "Checked every bolt myself, %N.|The %C's spot on."
Data "Best she's felt all season.|Don't waste it, %N."
Data "%C's singing today.|Go make some noise of your own."
Data "Not even a squeak out of her.|Perfect, %N. Off you go."
Data "She'll do everything you ask, %N.|Just don't ask everything at once."
Data "Full marks, %N. The %C's|ready for whatever's out there."
Data "%C's tip-top. Go show|the others how it's done."
Data "She's as good as she gets, %N.|No excuses left."
Data "Fresh oil, fresh tyres, fresh chance, %N."
Data "PRE_WORN", 18
Data "Bit of wear, %D%, %N.|Nothing you didn't cause yourself."
Data "%D% damage, %N.|Driving like that'll do it."
Data "She's a bit tired, %D%.|So would you be, with you behind the wheel."
Data "%D%, %N. Relax, it's not|your driving. Okay, it's a bit your driving."
Data "Nothing major at %D%, %N.|Your reputation's taken worse."
Data "%D% worn, %N.|She'll survive. Your ego's the question."
Data "A few niggles, %D%.|Same as your qualifying record, %N."
Data "%D%, %N. Don't worry -|everyone thrashes a car this badly once."
Data "She's showing %D%, %N.|You're showing a lack of remorse."
Data "%D% and a shimmy, %N.|Bit like your driving line, really."
Data "Tyres down a bit, %D%, %N.|Ease off. Or don't. I'm not your mum."
Data "%D%, %N. Not pretty.|Bit like that overtake you tried."
Data "She's carrying %D% like a champ, %N.|Wish I could say the same for you."
Data "Bit of a wobble at %D%, %N.|We'll blame the car, shall we?"
Data "%D%, %N. Keep both hands|on the wheel. Might help this time."
Data "She's tired, %D%, %N.|Aren't we all, dealing with you."
Data "%D% worn, %N.|She'll manage. You, less confident about."
Data "Only %D%, %N.|Honestly? Lower than I expected from you."
Data "PRE_BAD", 16
Data "%D% damage, %N.|That's not wear, that's a cry for help."
Data "Brakes are cooked, %D%, %N.|So's your technique, clearly."
Data "%D%, %N. I wouldn't drive her.|But then, I can actually drive."
Data "She's hurting at %D%, %N.|Nurse her home. Nurse your pride too."
Data "%D% and getting worse, %N.|Bit like your excuses."
Data "Gearbox is crunchy, %D%, %N.|So is your gear selection, evidently."
Data "%D% damage, %N. That's a lot of|prayer for someone who drives like that."
Data "She's not happy at %D%, %N.|Neither am I, watching you drive her."
Data "%D%, %N. I'd call it terminal.|Your excuses too, probably."
Data "Something's grinding at %D%, %N.|Try not to think about the bill."
Data "%D% and the steering's vague, %N.|Explains a lot about your last lap."
Data "She's coughing at %D%, %N.|Can't blame her, watching you drive."
Data "%D% damage, %N. I'd fix her|if you had the cash and I had the patience."
Data "%D%, %N. On borrowed time,|much like my patience with you."
Data "%D%, %N. She'll get you round.|No promises, and no compliments either."
Data "%D% damage, %N.|Impressive, in the worst way."
Data "PRE_CRITICAL", 12
Data "%D% damage, %N.|I've seen better cars in a wrecking yard."
Data "%D%. Honestly? I'd walk.|Slower than your last lap, mind."
Data "If a wheel comes off, %N,|you didn't hear it from me."
Data "%D% damage. She's more rust|than car, %N - much like your record."
Data "%D%, %N. I've said my piece.|Your funeral, your driving."
Data "Closer to scrap than a race|car, %N - and so are you, frankly."
Data "%D% damage, %N. Not my|responsibility what happens next."
Data "She's on her last legs, %N.|%D% and counting. Impressive, somehow."
Data "%D%. Get a HOT LAP in and REPAIR her,|%N, before you do more damage."
Data "She might not finish, %N.|%D% damage. Up to you and your ego."
Data "%D%, %N. I've seen coffins|in better shape. So has your instructor."
Data "I've done what I can, %N.|%D% left. The rest is on you."
Data "PRER", 30
Data "Let's do this!"
Data "Keep the kettle on."
Data "Full throttle, no brakes."
Data "Just bring me home in one piece."
Data "Time to see what she can do."
Data "Brakes are for the weak."
Data "Green light, here I come!"
Data "I've been practising on the PlayStation."
Data "Tell my mum I love her."
Data "Pole position or bust!"
Data "Nobody panic, I know what I'm doing."
Data "Watch and learn, everyone."
Data "This is it. This is the one."
Data "I can taste the trophy already."
Data "Somebody time me, I'm feeling fast."
Data "Right, seatbelt's on. Let's go."
Data "If I'm not back in five, send help."
Data "I've got a good feeling about this lap."
Data "No fear, no brakes, no worries."
Data "History's about to be made."
Data "Let the record show I called this win."
Data "Deep breath. Here we go."
Data "This corner's mine today."
Data "I didn't come here to finish second."
Data "Somebody hold my drink, this is serious."
Data "Engines ready, nerves not so much."
Data "Last one to the flag buys the chips."
Data "I've dreamt about this exact moment."
Data "Right, hands at ten and two, brain switched on."
Data "Watch this. No, actually watch this."
Data "BILL", 18
Data "%N, your %C came in with %E.|That's $%M, mate."
Data "Bad news, %N - %E|on the %C. $%M."
Data "The %C had %E.|$%M. Cash or card?"
Data "%E, %N. I've seen worse.|Not much worse. $%M."
Data "Well, the %C finished.|%E though - $%M."
Data "Sounded expensive out there.|%E, $%M, %N."
Data "%N, brace yourself. %E.|$%M, and that's the mates' rate."
Data "The %C's got a story to tell -|%E. $%M to hear the ending."
Data "%E on the %C, %N.|$%M and we'll say no more about it."
Data "Not the %C's finest hour, %N -|%E. $%M please."
Data "%E, %N. Add it to the list.|$%M this time round."
Data "The damage report reads '%E'.|$%M, %N. Try not to wince."
Data "%N, the %C's back with %E.|$%M - I'll start the paperwork."
Data "Another one for the books - %E.|$%M, %N, cash preferred."
Data "%E this time, %N.|$%M. Could've been worse, honestly."
Data "The %C came home talking about %E.|$%M to make it stop."
Data "%N, %E again. $%M.|You're keeping me in business."
Data "Bit of %E out there, %N.|$%M and she'll be right."
Data "BILLR", 18
Data "Ouch. Just fix it!"
Data "There goes my budget..."
Data "Make it faster while you're in there."
Data "It was like that when I got it!"
Data "Worth every cent."
Data "Put it on the tab."
Data "Can I pay in lollies?"
Data "Was it the kerbs? It was the kerbs."
Data "That's what insurance is for. Isn't it?"
Data "In my defence, it was a great lap."
Data "I regret nothing. Well, maybe a bit."
Data "Fine, fine, take the money."
Data "Worth it for the overtake alone."
Data "Can you fix the dents in my pride too?"
Data "I'll pay you back in favours."
Data "The other guy started it."
Data "Does it come with a loyalty discount?"
Data "Highway robbery. See you next race."
Data "CLEAN", 18
Data "Clean race, %N! Nice win.|No work for me today."
Data "Winner! And not a scratch.|That's how it's done."
Data "Brilliant, %N! The %C's|in one piece AND a winner."
Data "What a drive! I'll just|polish the trophy then."
Data "Nothing to fix and a win.|Best day of my week, %N."
Data "Not a mark on her, %N!|You're making my job too easy."
Data "%N wins clean! The %C's|spotless - do it again."
Data "Perfect drive, %N. I'll just|put my tools away, then."
Data "The %C's untouched, %N.|Best kind of win there is."
Data "Flawless, %N! I might frame|the %C's paint job."
Data "Not even the tyres are worried, %N.|Clean win, clean car."
Data "%N drives like she's made of glass -|and wins anyway. Respect."
Data "A win and no bill, %N.|Don't get used to it."
Data "The %C looks showroom fresh, %N.|And she just won!"
Data "Textbook stuff, %N.|Not a scratch, not a worry."
Data "%N, you've spoiled me.|A win with nothing to fix."
Data "That's how you do it, %N.|Fast and untouched."
Data "%N takes it clean.|I'm almost disappointed I'm not busy."
Data "CLEANR", 18
Data "Couldn't have done it without you!"
Data "Easy."
Data "Did you see that last corner?"
Data "Drinks are on me!"
Data "The %C did all the work."
Data "I told you I had it in me."
Data "Clean and mean, that's how I roll."
Data "Not a scratch and a win - my favourite combo."
Data "Somebody frame that lap, please."
Data "I barely broke a sweat out there."
Data "That's what skill looks like."
Data "Front to back, no drama. Perfect."
Data "I'll take a bow now, thanks."
Data "The %C and I make a good team."
Data "That's going straight in my highlight reel."
Data "Nothing to it, honestly."
Data "Somebody pinch me, that was too easy."
Data "Book me in for next week too."
Data "TOODMG", 12
Data "She's not fit to race, %N -|%D% damage. Put in a HOT LAP|to earn the repairs, then REPAIR."
Data "No way, %N. %D% damage.|She'd fall apart on the grid.|HOT LAP first, then REPAIR."
Data "The %C stays here, %N.|%D%! Earn some cash on a|HOT LAP and I'll fix her."
Data "%D% damage, %N. That's a DNF|waiting to happen. HOT LAP first."
Data "I'm not signing off on %D%, %N.|HOT LAP her, then we'll talk REPAIR."
Data "The %C's grounded at %D%, %N.|Earn the fix money, then REPAIR."
Data "%D%! Not on my watch, %N.|HOT LAP first, REPAIR after."
Data "She won't survive a race at %D%, %N.|HOT LAP, then REPAIR, in that order."
Data "%D% damage is a park job, %N,|not a race day. HOT LAP first."
Data "I like you, %N, but %D%|is where I draw the line. HOT LAP."
Data "%D%, %N. That's the %C telling you|to slow down, not speed up."
Data "Not today, %N - %D%.|Go earn her keep on a HOT LAP."
Data "TOODMGR", 16
Data "Right. One flying lap it is."
Data "Fine, fine."
Data "How much for a quick fix?"
Data "She looks fine to me!"
Data "You're the boss, I suppose."
Data "One hot lap coming right up."
Data "Spoilsport."
Data "Fine, I'll earn my own repairs."
Data "This seems excessive."
Data "She's driven worse, trust me."
Data "Alright, alright, watch and learn."
Data "I'll show you a hot lap."
Data "Can't argue with the mechanic, I guess."
Data "One lap, coming up."
Data "Fine. But I'm still right."
Data "Off to prove a point, then."
Data "VISITR", 18
Data "Thanks, mate."
Data "Good to know."
Data "Keep her sweet for me."
Data "Any chance of more horsepower?"
Data "Cheers, see you on race day."
Data "Appreciate the honesty."
Data "You're a good bloke, you know that?"
Data "Right, noted. Anything else?"
Data "Good to hear she's holding up."
Data "You look after that car better than I do."
Data "Solid. Catch you next race."
Data "Wouldn't trust anyone else with her."
Data "Nice one. I'll let you get back to it."
Data "That's what I like to hear."
Data "You're worth every cent, mate."
Data "Good man. See you round."
Data "Cheers for keeping her honest."
Data "Right, I'll leave her in your hands."
Data "VISITBADR", 16
Data "How much to fix her?"
Data "Can you work miracles?"
Data "Don't tell me the number."
Data "Is that bad? That sounds bad."
Data "Be gentle with the news."
Data "I don't want to know, do I."
Data "How long have I got?"
Data "Say it slowly."
Data "Just tell me she'll live."
Data "This is why I don't visit more."
Data "Worse than last time?"
Data "I should've stayed home."
Data "Give it to me straight."
Data "Should I be sitting down?"
Data "Right, how bad on a scale of 'fine' to 'scrap'?"
Data "I'm almost scared to ask."
Data "SELL", 12
Data "Sorry to see her go, %N.|$%M - fair price."
Data "The %C for $%M. Done.|She'll miss you. I won't."
Data "Selling the %C? $%M, and|I'll give her a good home."
Data "$%M for the %C.|Pleasure doing business, %N."
Data "$%M, %N, and she's off the books.|End of an era."
Data "The %C moves on for $%M.|You made the right call, %N."
Data "$%M in your pocket, %N.|The garage'll feel emptier."
Data "Deal done, %N - $%M.|Someone else's problem now."
Data "$%M for the %C.|No hard feelings, %N."
Data "That's $%M, %N.|She was a good little earner."
Data "$%M, and the %C's someone|else's headache now, %N."
Data "Fair price, %N - $%M.|She deserves a good next owner."
Data "SELLR", 12
Data "She was a good 'un."
Data "Time for something faster."
Data "Don't cry, %C."
Data "I'll be back for her one day."
Data "End of an era, that."
Data "New car, who dis."
Data "She taught me everything I know."
Data "Onwards and upwards."
Data "I'll never forget our first win together."
Data "Selling her feels wrong, but here we are."
Data "May she treat her next owner kindly."
Data "That's a chapter closed."
Data "HOTGO", 12
Data "Right, %N, one flying lap.|Beat %Xs and there's money in it."
Data "Hot lap time! Target %Xs.|Go hard, %N."
Data "Clock's ready. Beat %Xs|and I'll open the cash box."
Data "One lap, no traffic, %N.|%Xs is the number."
Data "Empty track, %N. Beat %Xs|and it's payday."
Data "%Xs is the number to beat, %N.|Show me what she's got."
Data "One shot, %N. %Xs or nothing.|Clock's running."
Data "Clean lap, no excuses, %N.|Beat %Xs and get paid."
Data "%Xs, %N. Easy to say,|harder to do. Off you go."
Data "The stopwatch doesn't lie, %N.|%Xs is the target."
Data "Your call, %N. %Xs or bust.|Ready when you are."
Data "Just you and the clock, %N.|%Xs to beat."
Data "HOTGOR", 16
Data "Watch this!"
Data "Easy money."
Data "Hold my helmet. Wait, no."
Data "Stopwatch ready?"
Data "Here goes nothing!"
Data "This one's for the highlight reel."
Data "Clock's about to get a shock."
Data "I was born ready for this."
Data "Watch the number, not me."
Data "One lap. All business."
Data "Let's make that stopwatch sweat."
Data "No pressure. Lots of pressure."
Data "This is where legends are made."
Data "Full send, no regrets."
Data "I can already hear the cash box."
Data "Here we go - eyes on the clock!"
Data "HOTWIN", 10
Data "What a lap! %Ts.|That's $%M for the kitty."
Data "%Ts! Blistering, %N.|$%M is yours."
Data "Under the target! %Ts.|Here's $%M, champ."
Data "I nearly dropped the watch.|%Ts - $%M, well earned."
Data "%Ts, %N! That's a proper lap.|$%M, don't spend it all at once."
Data "Stopwatch says %Ts, %N.|$%M for that beauty."
Data "%Ts! You beat the number|by a mile. $%M, %N."
Data "That's quick, %N - %Ts.|$%M, straight into your pocket."
Data "%Ts, %N. The %C's never|gone that fast. $%M."
Data "Textbook, %N. %Ts.|$%M, and I mean every cent."
Data "HOTWINR", 12
Data "Told you!"
Data "Too easy."
Data "Put it towards the repairs."
Data "Again? Again!"
Data "That's what I call driving."
Data "Somebody frame that stopwatch reading."
Data "Told you I had it in me."
Data "That lap felt perfect."
Data "Money for jam, that was."
Data "I could do that all day."
Data "Stick that in the record books."
Data "Not bad for one lap, eh?"
Data "HOTLOSE", 9
Data "%Ts... the target was %Xs.|No money this time, mate."
Data "%Ts. Close, but %Xs was|the number. Nothing today."
Data "Missed it - %Ts against %Xs.|Better luck next time, %N."
Data "%Ts. My nan does %Xs|in her Corolla."
Data "%Ts, %N. So close, and yet.|%Xs was the ask."
Data "Not quite, %N - %Ts against %Xs.|No cash, no drama."
Data "%Ts. The %C had more in her,|but %Xs wasn't it today."
Data "Off the pace, %N - %Ts.|%Xs next time, maybe."
Data "%Ts against a %Xs target, %N.|Nothing in the till today."
Data "HOTLOSER", 10
Data "The car's holding me back!"
Data "The wind was against me."
Data "The watch is broken."
Data "I'll get it next time."
Data "That corner cost me, not the car."
Data "In my defence, the sun was in my eyes."
Data "Recalibrate that stopwatch, I reckon."
Data "One bad gear change, that's all it was."
Data "I was pacing myself. Strategically."
Data "Next time I'll actually try."
Data "FIXNONE", 12
Data "Nothing to fix, %N -|she's in perfect nick."
Data "The %C's spotless.|Did you drive her at all?"
Data "Not a scratch. Go and|race her, %N!"
Data "Nothing on the clipboard, %N.|The %C's clean as a whistle."
Data "I looked twice, %N.|Genuinely nothing to charge you for."
Data "The %C doesn't need me today, %N.|Go enjoy that."
Data "Zero damage, %N. Feels wrong|not charging you for something."
Data "She's perfect, %N. Frankly|it's a bit suspicious."
Data "Not a mark, %N. Are you even|racing this thing?"
Data "Clean bill of health, %N.|Get back out there."
Data "The %C's in showroom nick, %N.|Nothing for me to do here."
Data "Squeaky clean, %N.|My tools are staying in the box."
Data "FIXNONER", 12
Data "Just checking!"
Data "Can you polish her anyway?"
Data "Fair enough."
Data "Better safe than sorry, right?"
Data "I like to be thorough."
Data "Worth asking, I reckon."
Data "Can't be too careful."
Data "Good, good. Carry on."
Data "Just wanted to hear you say it."
Data "Suspiciously good news."
Data "I'll take it."
Data "No complaints here."
Data "SKINT", 12
Data "That's $%M of work|and you're skint, mate.|Try a HOT LAP."
Data "$%M to fix and your wallet's|empty. HOT LAP, %N."
Data "No money, no repairs, %N.|Earn it on a HOT LAP."
Data "%N, $%M's the bill and you're|light on cash. HOT LAP time."
Data "I'd fix her for $%M, %N,|but your wallet says no. HOT LAP."
Data "Can't run a charity, %N.|$%M owed - go HOT LAP it."
Data "$%M short, %N. The %C waits|till you've earned it."
Data "No credit here, %N.|$%M or a HOT LAP, your pick."
Data "$%M, %N. Come back|when the wallet's heavier."
Data "The tab's not that long, %N,|but $%M's still $%M. HOT LAP."
Data "Sorry, %N - $%M and you're|cleaned out. HOT LAP first."
Data "$%M owing, %N. Earn it,|then we'll fix her properly."
Data "SKINTR", 12
Data "Put it on my tab?"
Data "Can I pay in exposure?"
Data "I'll be back."
Data "Story of my life, this."
Data "Money troubles, always money troubles."
Data "Fine. I'll go earn it the hard way."
Data "Can't a driver catch a break?"
Data "Alright, watch this hot lap then."
Data "I'll be rich one day. Not today."
Data "Cash flow issues, that's all this is."
Data "Wallet's light, spirit's heavy."
Data "One hot lap and I'm square, right?"
Data "FIXED", 12
Data "All fixed - good as new.|That's $%M, cheers."
Data "The %C's like new, %N.|$%M, thanks very much."
Data "Straightened her out.|$%M - and I threw in a wash."
Data "Done! $%M. Try to|bring her back in one piece."
Data "Good as gold, %N. $%M,|and she's ready to race."
Data "%N, the %C's sorted - $%M.|Back to zero damage."
Data "$%M and she's brand new again, %N.|Try to keep it that way."
Data "All sorted, %N. $%M.|Not a dent left on her."
Data "$%M well spent, %N.|The %C's fighting fit."
Data "Fixed and fettled, %N. $%M.|She'll thank you out there."
Data "%N, $%M and the %C's|back to her best."
Data "Good as new, %N.|$%M - worth every cent, trust me."
Data "FIXEDR", 12
Data "Worth every cent."
Data "She's gorgeous."
Data "Thanks, mate!"
Data "Ouch, but OK."
Data "Like a whole new car."
Data "You're a miracle worker."
Data "Feels lighter already. Probably my wallet."
Data "Back in business!"
Data "She purrs again. Beautiful."
Data "Cheers, I owe you one."
Data "Right, let's go dent her again."
Data "That's the good stuff right there."
Data "PART", 10
Data "Did what I could for $%M.|She's at %D% now."
Data "$%M got you this far -|%D% damage left."
Data "That's all your $%M buys.|%D% still to go, %N."
Data "$%M spent, %N. Got her down|to %D%. Come back when you can."
Data "Patched what I could for $%M, %N.|%D% left - not perfect, but going."
Data "%N, $%M covers this much - %D%|still needs sorting when you're flush."
Data "Half a fix for half the cash, %N.|$%M down, %D% to go."
Data "$%M, %N. Better than nothing -|%D% remains, mind."
Data "Did my best with $%M, %N.|%D% left on the clock."
Data "$%M stretches this far, %N.|%D% still owing on her."
Data "PARTR", 10
Data "Better than nothing."
Data "I'll find the rest."
Data "Half a car is still a car."
Data "Every bit helps, I suppose."
Data "It'll do for now."
Data "Baby steps, I guess."
Data "I'll scrounge up the rest somehow."
Data "Progress is progress."
Data "She's better than she was, at least."
Data "One step closer to whole."
Data "BROKE", 12
Data "You're skint, %N - $%M left.|HOT LAP the %C to earn|your entry money."
Data "$%M won't get you on the grid.|Earn some on a HOT LAP, %N."
Data "Wallet's empty, %N.|The %C can earn it back -|GARAGE, HOT LAP."
Data "No entry fee, no race.|Go and earn it, %N!"
Data "%N, $%M's not enough to enter.|HOT LAP the %C for the shortfall."
Data "Can't race on fumes, %N.|$%M left - go HOT LAP it up."
Data "The entry fee doesn't negotiate, %N.|$%M short. HOT LAP time."
Data "$%M, %N. That's a HOT LAP|away from a race, not a race."
Data "No cash, no grid spot, %N.|The %C can earn it - HOT LAP."
Data "%N, you're $%M light.|Go make it up on a HOT LAP."
Data "Empty pockets don't enter races, %N.|HOT LAP first."
Data "$%M in the kitty, %N -|not enough. HOT LAP the difference."
Data "BROKER", 12
Data "Where did it all go?"
Data "One hot lap, coming up."
Data "Can I sell a tyre?"
Data "Money's for spending, right?"
Data "This is a temporary setback."
Data "Rich in spirit, poor in cash."
Data "Watch me earn it back in one lap."
Data "I blame the entry fees, honestly."
Data "Time to put the pedal down for real money."
Data "I'll be flush again by lap's end."
Data "Desperate times call for desperate hot laps."
Data "Right, one lap to save my racing career."
Data "PODIUM", 23
Data "Fair dinkum, %N! %P in the %C -|flat out like a lizard drinking. $%M."
Data "Bloody oath, %N! %P place.|Stick that $%M on the shelf with the trophy."
Data "You beauty, %N - %P in the %C!|Chuck another snag on the barbie. $%M."
Data "Too easy, %N. %P place, no dramas.|The %C's a bloody good car. $%M for you."
Data "Ripper drive, %N! %P in the %C.|That's $%M - reckon that deserves a coldie."
Data "Onya, %N! %P place is no fluke.|The %C's a little ripper. $%M, mate."
Data "Bonzer effort, %N! %P in the %C -|reckon that's worth a shrimp on the barbie. $%M."
Data "Strewth, %N! %P place and she's|running like a cut snake. $%M for your trouble."
Data "You little ripper, %N! %P in the %C -|she's a bloody weapon. $%M in your pocket."
Data "Good on ya, %N! %P place, easy as.|The %C didn't miss a beat. $%M, no worries."
Data "Legend, %N! %P in the %C -|reckon that's a yarn for the pub. $%M."
Data "Fair crack, %N! %P place and|not a drama all day. $%M for the effort."
Data "Beauty, %N! %P in the %C -|she went like a cut cat. $%M."
Data "Solid as, %N! %P place.|The %C did the business - $%M."
Data "Spot on, %N! %P in the %C -|textbook stuff. $%M, mate."
Data "Ace drive, %N! %P place, no worries at all.|$%M and a cold one waiting."
Data "Cracking run, %N! %P in the %C -|reckon she's got wings. $%M."
Data "Beauty of a drive, %N! %P place.|The %C earned every dollar - $%M."
Data "You ripper, %N! %P in the %C -|that's how it's done. $%M."
Data "Well driven, %N! %P place,|no arguments there. $%M for your trouble."
Data "Nice one, %N! %P in the %C -|clean as they come. $%M."
Data "Top shelf stuff, %N! %P place.|The %C's a weapon - $%M."
Data "Bloody brilliant, %N! %P in the %C -|reckon that's a keeper. $%M."
Data "PODIUMR", 23
Data "Too easy, mate!"
Data "She's a beauty, this car!"
Data "Get amongst it, that's what I say!"
Data "Chuck us the trophy, I've earned it."
Data "Is very good day for me, yes yes!"
Data "My English not so good, but trophy|- he speak all language!"
Data "I am so happy, my heart go very fast,|like the car!"
Data "Today everything, how you say,|click into places!"
Data "Crikey, that was close out there!"
Data "Beers all round - I am buying, maybe!"
Data "No worries at all, she goes|like a rocket, this one!"
Data "Is best day of my whole life,|I think, maybe top three!"
Data "Cor, look at that trophy shine -|better than my last girlfriend!"
Data "Next time, even faster, you watch -|I promise this, no worries!"
Data "Is unbelievable! I practice so much,|now look, podium, yes!"
Data "My whole village will hear|about this, I promise you!"
Data "I dedicate this podium to|my car, my only true friend!"
Data "You see this smile? This smile|is not coming off, no way!"
Data "Champagne? No, I prefer the|victory itself, but yes, also champagne!"
Data "I call my mother right now,|she will not believe this!"
Data "Podium is nice, but next time|- first place, you wait and see!"
Data "Even my rivals must admit,|today I was simply the best!"
Data "This trophy, I sleep with it tonight,|I am not even joking!"
Data "LEAVE", 20
Data "Righto, %N. Sorry to see you go -|the garage door's always open."
Data "Fair winds, %N. It's been a|pleasure having you round the traps."
Data "Off you go then, %N.|Thanks for the memories, mate."
Data "See you round, %N.|Leave your helmet - only joking."
Data "All the best, %N.|Come back and race us again sometime."
Data "Sad to lose you, %N.|The %C's spot stays open."
Data "Take care, %N. It's been|a pleasure having you in the garage."
Data "%N's off! Good luck out there,|wherever the road takes you."
Data "Don't be a stranger, %N.|We'll keep the kettle warm."
Data "Right, %N. Last one out,|turn the pit lights off."
Data "It's been good, %N.|The team won't be the same."
Data "Off into the sunset, %N.|Drive safe, wherever you're headed."
Data "%N, you'll always have a seat here.|Come back any time."
Data "Godspeed, %N. The garage|remembers every lap you ran."
Data "Take it easy, %N.|Thanks for the good times."
Data "%N's calling it. Fair enough.|Door's open whenever."
Data "Cheers for everything, %N.|The %C's story isn't over yet."
Data "All the best out there, %N.|You'll be missed round here."
Data "Righto then, %N. Safe travels,|and thanks for the laughs."
Data "%N heads off into the sunset.|The garage salutes you."
Data "LEAVER", 20
Data "Thanks for everything, mate."
Data "It's been a blast - see ya!"
Data "Catch you all at the next one."
Data "Look after the old girl for me."
Data "Cheers, team. This isn't goodbye!"
Data "I'll be back, one way or another."
Data "This garage'll always be home."
Data "Onwards to the next adventure."
Data "Keep a seat warm for me."
Data "Thanks for putting up with me."
Data "It's not goodbye, just see you later."
Data "Best team I've ever raced with."
Data "Take care of yourselves, all of you."
Data "I'll tell everyone about this place."
Data "Until next time, legends."
Data "Wouldn't trade these laps for anything."
Data "See you on the track someday."
Data "Thanks for the ride, literally."
Data "This isn't the last you'll see of me."
Data "Catch you all later, team."
Data "GARAGE", 20
Data "Right, who's next?"
Data "G'day! Ready when you are."
Data "Garage is open - what'll it be?"
Data "Kettle's on. Who's racing?"
Data "Bring 'em in, one at a time."
Data "Tyres are warm and I'm not busy."
Data "Another day, another engine to fettle."
Data "Who's up first, then?"
Data "Quiet one today. Suits me fine."
Data "Right, tools are out. Who needs what?"
Data "Garage doors are open, come on in."
Data "Good morning, or afternoon, whatever it is."
Data "All quiet on the western front."
Data "Ready for whatever you throw at me."
Data "Business as usual round here."
Data "Someone's due for a visit, surely."
Data "Standing by, as always."
Data "The garage never sleeps. Neither do I, apparently."
Data "Who's brave enough to go first today?"
Data "Let's see what today brings."
Data "END", 0

' a line for the moment cat$, with the %N %C ... filled in
Function Quote$(cat$)
  Local string c$, t$
  Local integer n, i, k, r
  Restore QuoteBank
  Do
    Read c$, n
    If c$ = "END" Then Exit Function
    If c$ = cat$ Then
      ' shuffle bag: every line said once before any repeat (qSaid, one
      ' bit per line), and never immediately the same one as last time
      ' even across a reshuffle (qLast holds that line + 1). Once every
      ' line's bit is set the bag's empty -- clear it and start again
      If (qSaid(k) And ((1 << n) - 1)) = (1 << n) - 1 Then qSaid(k) = 0
      Do
        r = Int(Rnd * n)
      Loop While n > 1 And ((qSaid(k) And (1 << r)) <> 0 Or r = qLast(k) - 1)
      qSaid(k) = qSaid(k) Or (1 << r)
      qLast(k) = r + 1
      For i = 0 To r
        Read t$
      Next
      Quote$ = FillIn$(t$)
      Exit Function
    EndIf
    For i = 1 To n
      Read t$
    Next
    k = k + 1
  Loop
End Function

' t$ with its %N %C %D %M %T %X %E filled in -- one pass, two small
' strings (the PICO3's string heap is small, and this runs while a
' scene is already holding its lines)
Function FillIn$(t$)
  Local string o$, k$
  Local integer i
  i = 1
  Do While i <= Len(t$)
    k$ = Mid$(t$, i, 1)
    If k$ = "%" And i < Len(t$) Then
      k$ = Mid$(t$, i + 1, 1)
      i = i + 2
      Select Case k$
        Case "N"
          o$ = o$ + qN$
        Case "C"
          o$ = o$ + qC$
        Case "D"
          o$ = o$ + qD$
        Case "M"
          o$ = o$ + qM$
        Case "T"
          o$ = o$ + qT$
        Case "X"
          o$ = o$ + qX$
        Case "E"
          o$ = o$ + qE$
        Case "P"
          o$ = o$ + qP$
        Case Else
          ' a plain % (as in "45% damage"): keep it, and the next letter
          o$ = o$ + "%"
          i = i - 1
      End Select
    Else
      o$ = o$ + k$
      i = i + 1
    EndIf
  Loop
  FillIn$ = o$
End Function
